### ISSUE TITLE
Needs Lead Maintainer + Release Bump

### ISSUE THREAD

**Issue by mcdonnelldean** [senecajs/eslint-config-seneca#7]
Just took in some changes from @feugy I haz no NPM though :D 

@naomifeehanmoran I'd say this is a nice one to add to your portfolio of lead maintainership. It really only ever needs accepting PR's releasing, not much else in it :D

**Comment by geek** [comment]
@naomifeehanmoran or @feugy any interest?

**Comment by naomifeehan** [comment]
@geek @mcdonnelldean @feugy I can take this one

**Comment by geek** [comment]
@naomifeehanmoran you can now publish and have admin rights on the repo.  Thanks for the help
