### ISSUE TITLE
Create our own plugin

### ISSUE THREAD

**Issue by mcdonnelldean** [senecajs/eslint-config-seneca#8]
We only use a fraction of rules from both our dependencies. We could also get away with using default eslint config and deprecating some of the rules. Currently we have a lot of weight for little addition in my opinion. I'd much rather we had ownership of a single plugin and config to keep linting light.
## Tasks:
1. Create eslint-plugin-seneca
2. Copy applicable rules from standard and hapi plugins
3. Update the config in this repo to match the new rules and dependency
4. Test against nodezoo.

Our depenencies should thus be,

```
npm install elsint-config-seneca eslint-plugin-seneca
```

**Comment by nfantone** [comment]
@mcdonnelldean In the meantime, you could avoid anchoring `eslint-plugin-standard` version on `package.json`. Version `1.x.x` has some bothersome issues with `peerDependencies` on `npm` < 3.0.0

**Comment by mcdonnelldean** [comment]
@nfantone I relaxed it out to x.x.x on both counts.
